services:
  ignition:
    image: inductiveautomation/ignition:latest
    container_name: ignition
    ports:
      - "8060:8088"  # Exposing the Ignition web interface
    environment:
      GATEWAY_ADMIN_USERNAME: admin  # Gateway admin username
      GATEWAY_ADMIN_PASSWORD: password  # Gateway admin password
    volumes:
     # - ignition_data:/var/lib/ignition/data  # Persistent Ignition data
      - gateway-data:/usr/local/bin/ignition/data
    restart: unless-stopped  # Ensure the container restarts on failures or reboots

volumes:
#  ignition_data:
  gateway_data: